Debug

diff --git a/.github/workflows/rename-pr.yml b/.github/workflows/rename-pr.yml
--- a/.github/workflows/rename-pr.yml
+++ b/.github/workflows/rename-pr.yml
@@ -17,21 +17,28 @@ jobs:
         id: skip
         run: echo "Run not needed for this PR, skipping remaining steps"
 
+      # - name: Get Jira issue key from PR branch name
+      #   if: steps.skip.outcome == 'skipped'
+      #   id: get_jira_issue_key
+      #   run: |
+      #     BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
+      #     echo "Branch name: $BRANCH_NAME"
+      #     ISSUE_KEY=$(echo ${{ BRANCH_NAME }} | grep -oE "^WA-\d+")
+      #     echo "Extracted ISSUE_KEY: $ISSUE_KEY"
+      #     if [[ -n $ISSUE_KEY ]]; then # if $ISSUE_KEY is not empty
+      #       echo "Extracted ISSUE_KEY: $ISSUE_KEY"
+      #       echo "jira_issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "No Jira issue key found in branch name."
+      #       exit 1 #TODO: Do we want a red fail here? Or just skip the rest of the steps?
+      #     fi
       - name: Get Jira issue key from PR branch name
         if: steps.skip.outcome == 'skipped'
         id: get_jira_issue_key
-        run: |
-          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
-          echo "Branch name: $BRANCH_NAME"
-          ISSUE_KEY=$(echo ${{ BRANCH_NAME }} | grep -oE "^WA-\d+")
-          echo "Extracted ISSUE_KEY: $ISSUE_KEY"
-          if [[ -n $ISSUE_KEY ]]; then # if $ISSUE_KEY is not empty
-            echo "Extracted ISSUE_KEY: $ISSUE_KEY"
-            echo "jira_issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT
-          else
-            echo "No Jira issue key found in branch name."
-            exit 1 #TODO: Do we want a red fail here? Or just skip the rest of the steps?
-          fi
+        run: .github/scripts/extract_issue_key.sh
+        env:
+          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
+          PROJECT: ${{ inputs.project }}
 
       - name: Echo status of get_jira_issue_key
         if: steps.skip.outcome == 'skipped'
